# Generated by Django 5.0.7 on 2024-07-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0005_rename_name_affiliation_abbreviated_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="status",
            field=models.CharField(default=None),
        ),
    ]
