# Generated by Django 5.0.7 on 2024-07-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0008_alter_affiliation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="abbreviated_name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
