# Generated by Django 5.0.7 on 2024-07-24 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0009_alter_affiliation_abbreviated_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affiliation",
            name="coordinator",
        ),
        migrations.RemoveField(
            model_name="affiliation",
            name="coordinator_email",
        ),
        migrations.CreateModel(
            name="Coordinator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coordinator_name", models.CharField()),
                ("coordinator_email", models.EmailField(max_length=254)),
                (
                    "affiliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="affiliations.affiliation",
                    ),
                ),
            ],
        ),
    ]
