# Generated by Django 5.0.7 on 2024-07-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0013_remove_affiliation_clinvar_submitter_ids_submitter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submitter",
            old_name="clinvar_submitter_id",
            new_name="submitter_id",
        ),
    ]
