# Generated by Django 5.0.7 on 2024-07-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0014_rename_clinvar_submitter_id_submitter_submitter_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submitter",
            old_name="submitter_id",
            new_name="clinvar_submitter_id",
        ),
    ]
