# Generated by Django 5.0.7 on 2024-07-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0016_affiliation_curation_panel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="affiliation_id",
            field=models.IntegerField(help_text="10000 number ID"),
        ),
        migrations.AlterField(
            model_name="affiliation",
            name="curation_panel_id",
            field=models.IntegerField(
                blank=True,
                help_text="GCEP or VCEP ID. If Independent Curation Group, leave this field blank.",
                null=True,
            ),
        ),
    ]
