# Generated by Django 5.0.7 on 2024-07-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0017_alter_affiliation_affiliation_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="abbreviated_name",
            field=models.CharField(
                blank=True, null=True, verbose_name="Abbreviated Name"
            ),
        ),
        migrations.AlterField(
            model_name="affiliation",
            name="affiliation_id",
            field=models.IntegerField(
                help_text="10000 number ID", verbose_name="Affiliation ID"
            ),
        ),
        migrations.AlterField(
            model_name="affiliation",
            name="clinical_domain_working_group",
            field=models.CharField(verbose_name="CDWG"),
        ),
        migrations.AlterField(
            model_name="affiliation",
            name="curation_panel_id",
            field=models.IntegerField(
                blank=True,
                help_text="GCEP or VCEP ID. If Independent Curation Group, leave this field blank.",
                null=True,
                verbose_name="Curation Panel ID",
            ),
        ),
        migrations.AlterField(
            model_name="affiliation",
            name="full_name",
            field=models.CharField(verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="approver",
            name="approver_name",
            field=models.CharField(verbose_name="Approver Name"),
        ),
        migrations.AlterField(
            model_name="coordinator",
            name="coordinator_email",
            field=models.EmailField(max_length=254, verbose_name="Coordinator Email"),
        ),
        migrations.AlterField(
            model_name="coordinator",
            name="coordinator_name",
            field=models.CharField(verbose_name="Coordinator Name"),
        ),
        migrations.AlterField(
            model_name="submitter",
            name="clinvar_submitter_id",
            field=models.CharField(verbose_name="ClinVar Submitter ID"),
        ),
    ]
