# Generated by Django 5.0.7 on 2024-08-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0018_alter_affiliation_abbreviated_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affiliation",
            name="curation_panel_id",
        ),
        migrations.AddField(
            model_name="affiliation",
            name="expert_panel_id",
            field=models.IntegerField(
                blank=True,
                help_text="GCEP or VCEP ID. If Independent Curation Group, leave this field blank.",
                null=True,
                verbose_name="Expert Panel ID",
            ),
        ),
    ]
