# Generated by Django 5.1 on 2024-08-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0019_remove_affiliation_curation_panel_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="status",
            field=models.CharField(
                choices=[
                    ("APPLYING", "Applying"),
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("RETIRED", "Retired"),
                ],
                verbose_name="status",
            ),
        ),
    ]
