# Generated by Django 5.1 on 2024-08-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "affiliations",
            "0022_alter_affiliation_clinical_domain_working_group_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="type",
            field=models.CharField(
                choices=[
                    ("VCEP", "Variant Curation Expert Panel"),
                    ("GCEP", "Gene Curation Expert Panel"),
                    ("INDEPENDENT_CURATION", "Independent Curation Group"),
                    ("SC_VCEP", "Somatic Cancer Variant Curation Expert Panel"),
                ],
                verbose_name="Type",
            ),
        ),
    ]
