# Generated by Django 5.1 on 2024-08-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0023_alter_affiliation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="expert_panel_id",
            field=models.IntegerField(
                blank=True,
                help_text="GCEP or VCEP ID. If Independent Curation Group or SC-VCEP, leave this field blank.",
                null=True,
                verbose_name="Expert Panel ID",
            ),
        ),
    ]
