# Generated by Django 5.1.1 on 2024-09-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0024_alter_affiliation_expert_panel_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affiliation",
            name="abbreviated_name",
        ),
        migrations.AddField(
            model_name="affiliation",
            name="short_name",
            field=models.CharField(blank=True, null=True, verbose_name="Short Name"),
        ),
        migrations.AlterField(
            model_name="affiliation",
            name="expert_panel_id",
            field=models.IntegerField(
                blank=True,
                help_text="GCEP or VCEP ID. If Independent Curation FGroup or SC-VCEP, leave this field blank.",
                null=True,
                verbose_name="Expert Panel ID",
            ),
        ),
    ]
