# Generated by Django 5.1 on 2024-09-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0024_alter_affiliation_expert_panel_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="affiliation_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Affiliation ID"
            ),
        ),
    ]
