# Generated by Django 5.1 on 2024-09-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0026_alter_affiliation_affiliation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="affiliation_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Affiliation ID"
            ),
        ),
    ]
