# Generated by Django 5.1 on 2024-09-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0030_alter_affiliation_affiliation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="affiliation_id",
            field=models.IntegerField(blank=True, verbose_name="Affiliation ID"),
        ),
    ]
