# Generated by Django 5.1 on 2024-09-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0031_alter_affiliation_affiliation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="expert_panel_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Expert Panel ID"
            ),
        ),
    ]
