# Generated by Django 5.1.1 on 2024-09-27 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0025_remove_affiliation_abbreviated_name_and_more"),
        ("affiliations", "0032_alter_affiliation_expert_panel_id"),
    ]

    operations = []
