# Generated by Django 5.1.2 on 2024-10-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliations", "0034_alter_affiliation_expert_panel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliation",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
